//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASDOTNET_DBFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Classroom
    {
        [StringLength(50)]
        public string className { get; set; }
        [Range(5,500)]
        public Nullable<int> capcity { get; set; }
        [StringLength(50)]
        public string classLocation { get; set; }
        public int ClassroomID { get; set; }
    }
}
