//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASDOTNET_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        public int Id { get; set; }
        public string color { get; set; }
        public string make { get; set; }
        public string purchaseDate { get; set; }
    }
}
