//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASDOTNET_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stationary
    {
        public string stationaryName { get; set; }
        public Nullable<int> price { get; set; }
        public string supplier { get; set; }
        public int StationaryID { get; set; }
    }
}
